package com.zx.back.mapper;

import com.zx.back.model.Flight;
import com.zx.back.model.FlightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     *
     */
    List<Flight> findBET(@Param("fBegin") String fBegin, @Param("fEnd") String fEnd, @Param("sTime") String sTime);


    //更新余座
    public void updateSeat(@Param("fid") String fid, @Param("seatsum") Integer seatsum);

    int countByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int deleteByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int insertSelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    List<Flight> selectByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    Flight selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int updateByExample(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int updateByPrimaryKeySelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated Fri Apr 12 17:51:48 CST 2019
     */
    int updateByPrimaryKey(Flight record);
}